# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_burp_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_import_burp_window(object):
    def setupUi(self, import_burp_window):
        import_burp_window.setObjectName("import_burp_window")
        import_burp_window.resize(577, 424)
        self.gridLayout = QtWidgets.QGridLayout(import_burp_window)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(import_burp_window)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_yes = QtWidgets.QPushButton(self.widget)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.gridLayout_2.addWidget(self.pushButton_yes, 0, 2, 1, 1)
        self.plainTextEdit_burp = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit_burp.setObjectName("plainTextEdit_burp")
        self.gridLayout_2.addWidget(self.plainTextEdit_burp, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(import_burp_window)
        QtCore.QMetaObject.connectSlotsByName(import_burp_window)

    def retranslateUi(self, import_burp_window):
        _translate = QtCore.QCoreApplication.translate
        import_burp_window.setWindowTitle(_translate("import_burp_window", "Form"))
        self.label.setText(_translate("import_burp_window", "一键导入数据包"))
        self.pushButton_yes.setText(_translate("import_burp_window", "确定"))
        self.plainTextEdit_burp.setPlaceholderText(_translate("import_burp_window", "请输入要导入的数据包，然后点击确定按钮"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    import_burp_window = QtWidgets.QWidget()
    ui = Ui_import_burp_window()
    ui.setupUi(import_burp_window)
    import_burp_window.show()
    sys.exit(app.exec_())
