# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vul_introduction_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vul_introduction_window(object):
    def setupUi(self, vul_introduction_window):
        vul_introduction_window.setObjectName("vul_introduction_window")
        vul_introduction_window.resize(560, 434)
        self.verticalLayout = QtWidgets.QVBoxLayout(vul_introduction_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_introduction = QtWidgets.QLabel(vul_introduction_window)
        self.label_introduction.setObjectName("label_introduction")
        self.verticalLayout.addWidget(self.label_introduction)
        self.plainTextEdit_introduction = QtWidgets.QPlainTextEdit(vul_introduction_window)
        self.plainTextEdit_introduction.setObjectName("plainTextEdit_introduction")
        self.verticalLayout.addWidget(self.plainTextEdit_introduction)
        self.widget_button = QtWidgets.QWidget(vul_introduction_window)
        self.widget_button.setObjectName("widget_button")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_button)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_yes = QtWidgets.QPushButton(self.widget_button)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout.addWidget(self.pushButton_yes)
        self.pushButton_no = QtWidgets.QPushButton(self.widget_button)
        self.pushButton_no.setObjectName("pushButton_no")
        self.horizontalLayout.addWidget(self.pushButton_no)
        self.verticalLayout.addWidget(self.widget_button)

        self.retranslateUi(vul_introduction_window)
        QtCore.QMetaObject.connectSlotsByName(vul_introduction_window)

    def retranslateUi(self, vul_introduction_window):
        _translate = QtCore.QCoreApplication.translate
        vul_introduction_window.setWindowTitle(_translate("vul_introduction_window", "漏洞-介绍编辑"))
        self.label_introduction.setText(_translate("vul_introduction_window", "漏洞介绍"))
        self.pushButton_yes.setText(_translate("vul_introduction_window", "确定"))
        self.pushButton_no.setText(_translate("vul_introduction_window", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vul_introduction_window = QtWidgets.QWidget()
    ui = Ui_vul_introduction_window()
    ui.setupUi(vul_introduction_window)
    vul_introduction_window.show()
    sys.exit(app.exec_())
